### ISSUE TITLE
Outdated pybind11

### ISSUE THREAD

**Issue by techdragon** [PyMesh/PyMesh#360]
The current version of pybind in the third_party submodules, is out of date and needs updating for more recent versions of python. I've done this in my own local install and it appears to work fine with pybind11 version 2.11

**Comment by qipaifeiying** [comment]
My operating system is Ubuntu 20.04, when I type make, it reports the error:
/home/qipaifeiying/workspace/PyMesh/third_party/pybind11/include/pybind11/cast.h:442:36: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
  442 |                 "  " + handle(frame->f_code->co_filename).cast<std::string>() +

I think I need to update pybind11. 
I would like to know how to update pybind11.
