### ISSUE TITLE
carve build problem

### ISSUE THREAD

**Issue by ellisk42** [PyMesh/PyMesh#258]
I'm having trouble building pymesh w/ carve using the install instructions (likely duplicate of https://github.com/PyMesh/PyMesh/issues/222, but that issue was closed without any comments):

Building third-party modules seems to work:

```
$ cat /etc/issue
Ubuntu 18.04.4 LTS \n \l

$ git clone https://github.com/PyMesh/PyMesh.git && cd PyMesh && git submodule update --init && export PYMESH_PATH=`pwd`

...

$ sudo apt-get install libeigen3-dev libgmp-dev libgmpxx4ldbl libmpfr-dev libboost-dev libboost-thread-dev libtbb-dev python3-dev

...

$ pip install -r $PYMESH_PATH/python/requirements.txt

...

$ cd third_party && python build.py all && cd ..

...

$ mkdir build && cd build && cmake ..

...
-- Build files have been written to: /home/ellisk/CSM/csm/third_party/PyMesh/build
```
But then I run `make` and get the following error:
```
$ make
Scanning dependencies of target Mesh
[  0%] Building CXX object src/CMakeFiles/Mesh.dir/Attributes/EdgeDihedralAngleAttribute.cpp.o
[  1%] Building CXX object src/CMakeFiles/Mesh.dir/Attributes/EdgeLengthAttribute.cpp.o
...
[ 56%] Building CXX object tools/Boolean/CMakeFiles/lib_Boolean.dir/BooleanEngine.cpp.o
In file included from /usr/local/include/carve/collection/unordered.hpp:29:0,
                 from /usr/local/include/carve/collection.hpp:20,
                 from /usr/local/include/carve/carve.hpp:51,
                 from /usr/local/include/carve/csg.hpp:24,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/Carve/CarveEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:20:
/usr/local/include/carve/collection/unordered/boost_impl.hpp:28:9: error: redeclared with 4 template parameters
   class unordered_map : public boost::unordered_map<Key, T, Hash, Pred> {
         ^~~~~~~~~~~~~
In file included from /usr/include/c++/7/unordered_map:48:0,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/config.h:636,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/basic.h:21,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Simple_cartesian.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/IGL/IGLEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:11:
/usr/include/c++/7/bits/unordered_map.h:101:11: note: previous declaration ‘template<class _Key, class _Tp, class _Hash, class _Pred, class _Alloc> class std::unordered_map’ used 5 template parameters
     class unordered_map
           ^~~~~~~~~~~~~
In file included from /usr/local/include/carve/collection/unordered.hpp:29:0,
                 from /usr/local/include/carve/collection.hpp:20,
                 from /usr/local/include/carve/carve.hpp:51,
                 from /usr/local/include/carve/csg.hpp:24,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/Carve/CarveEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:20:
/usr/local/include/carve/collection/unordered/boost_impl.hpp:36:9: error: redeclared with 4 template parameters
   class unordered_multimap : public boost::unordered_multimap<Key, T, Hash, Pred> {
         ^~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/unordered_map:48:0,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/config.h:636,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/basic.h:21,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Simple_cartesian.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/IGL/IGLEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:11:
/usr/include/c++/7/bits/unordered_map.h:72:11: note: previous declaration ‘template<class _Key, class _Tp, class _Hash, class _Pred, class _Alloc> class std::unordered_multimap’ used 5 template parameters
     class unordered_multimap;
           ^~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/carve/collection/unordered.hpp:29:0,
                 from /usr/local/include/carve/collection.hpp:20,
                 from /usr/local/include/carve/carve.hpp:51,
                 from /usr/local/include/carve/csg.hpp:24,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/Carve/CarveEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:20:
/usr/local/include/carve/collection/unordered/boost_impl.hpp:41:9: error: redeclared with 3 template parameters
   class unordered_set : public boost::unordered_set<Value, Hash, Pred> {
         ^~~~~~~~~~~~~
In file included from /usr/include/c++/7/unordered_set:48:0,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/config.h:635,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/basic.h:21,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Simple_cartesian.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/IGL/IGLEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:11:
/usr/include/c++/7/bits/unordered_set.h:96:11: note: previous declaration ‘template<class _Value, class _Hash, class _Pred, class _Alloc> class std::unordered_set’ used 4 template parameters
     class unordered_set
           ^~~~~~~~~~~~~
In file included from /usr/include/c++/7/bits/hashtable.h:35:0,
                 from /usr/include/c++/7/unordered_set:47,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/config.h:635,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/basic.h:21,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Simple_cartesian.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/IGL/IGLEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:11:
/usr/include/c++/7/bits/hashtable_policy.h: In instantiation of ‘struct std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >’:
/usr/include/c++/7/type_traits:143:12:   required from ‘struct std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > >’
/usr/include/c++/7/type_traits:154:31:   required from ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
/usr/include/c++/7/bits/unordered_set.h:98:63:   required from ‘class std::unordered_set<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> >’
/usr/local/include/carve/faceloop.hpp:89:13:   required from here
/usr/include/c++/7/bits/hashtable_policy.h:87:34: error: no match for call to ‘(const std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> >) (const std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>&)’
  noexcept(declval<const _Hash&>()(declval<const _Key&>()))>
           ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/bits/move.h:54:0,
                 from /usr/include/c++/7/bits/stl_pair.h:59,
                 from /usr/include/c++/7/bits/stl_algobase.h:64,
                 from /usr/include/c++/7/memory:62,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.h:4,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:2:
/usr/include/c++/7/type_traits: In instantiation of ‘struct std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’:
/usr/include/c++/7/bits/unordered_set.h:98:63:   required from ‘class std::unordered_set<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> >’
/usr/local/include/carve/faceloop.hpp:89:13:   required from here
/usr/include/c++/7/type_traits:154:31: error: ‘value’ is not a member of ‘std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > >’
     : public __bool_constant<!bool(_Pp::value)>
                               ^~~~~~~~~~~~~~~~
In file included from /usr/include/c++/7/unordered_set:48:0,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/config.h:635,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/basic.h:21,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Cartesian/Cartesian_base.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Simple_cartesian.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/python/pymesh/third_party/include/CGAL/Exact_predicates_exact_constructions_kernel.h:20,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/IGL/IGLEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:11:
/usr/include/c++/7/bits/unordered_set.h: In instantiation of ‘class std::unordered_set<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> >’:
/usr/local/include/carve/faceloop.hpp:89:13:   required from here
/usr/include/c++/7/bits/unordered_set.h:98:63: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef __uset_hashtable<_Value, _Hash, _Pred, _Alloc>  _Hashtable;
                                                               ^~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:105:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::key_type key_type;
                                             ^~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:106:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::value_type value_type;
                                               ^~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:107:43: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::hasher hasher;
                                           ^~~~~~
/usr/include/c++/7/bits/unordered_set.h:108:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::key_equal key_equal;
                                              ^~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:109:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::allocator_type allocator_type;
                                                   ^~~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:114:45: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::pointer  pointer;
                                             ^~~~~~~
/usr/include/c++/7/bits/unordered_set.h:115:50: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::const_pointer const_pointer;
                                                  ^~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:116:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::reference  reference;
                                               ^~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:117:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::const_reference const_reference;
                                                    ^~~~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:118:46: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::iterator  iterator;
                                              ^~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:119:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::const_iterator const_iterator;
                                                   ^~~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:120:51: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::local_iterator local_iterator;
                                                   ^~~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:121:57: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::const_local_iterator const_local_iterator;
                                                         ^~~~~~~~~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:122:47: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::size_type  size_type;
                                               ^~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:123:52: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       typedef typename _Hashtable::difference_type difference_type;
                                                    ^~~~~~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:282:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       operator=(initializer_list<value_type> __l)
       ^~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:375:2: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
  emplace(_Args&&... __args)
  ^~~~~~~
/usr/include/c++/7/bits/unordered_set.h:419:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       insert(const value_type& __x)
       ^~~~~~
/usr/include/c++/7/bits/unordered_set.h:423:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       insert(value_type&& __x)
       ^~~~~~
/usr/include/c++/7/bits/unordered_set.h:478:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       insert(initializer_list<value_type> __l)
       ^~~~~~
/usr/include/c++/7/bits/unordered_set.h:679:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       equal_range(const key_type& __x)
       ^~~~~~~~~~~
/usr/include/c++/7/bits/unordered_set.h:683:7: error: ‘value’ is not a member of ‘std::__not_<std::__and_<std::__is_fast_hash<std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > >, std::__detail::__is_noexcept_hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*>, std::hash<std::pair<carve::mesh::Vertex<3>*, carve::mesh::Vertex<3>*> > > > >’
       equal_range(const key_type& __x) const
       ^~~~~~~~~~~
In file included from /usr/local/include/carve/csg.hpp:34:0,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/Carve/CarveEngine.h:6,
                 from /home/ellisk/CSM/csm/third_party/PyMesh/tools/Boolean/BooleanEngine.cpp:20:
/usr/local/include/carve/intersection.hpp: In member function ‘bool carve::csg::Intersections::intersects(const carve::csg::IObj&, carve::csg::Intersections::edge_t*)’:
/usr/local/include/carve/intersection.hpp:120:21: error: ‘std::super<carve::csg::IObj, std::map<carve::csg::IObj, carve::mesh::Vertex<3>*, std::less<carve::csg::IObj>, std::allocator<std::pair<const carve::csg::IObj, carve::mesh::Vertex<3>*> > >, carve::csg::IObj_hash, std::equal_to<carve::csg::IObj>, std::allocator<std::pair<const carve::csg::IObj, std::map<carve::csg::IObj, carve::mesh::Vertex<3>*, std::less<carve::csg::IObj>, std::allocator<std::pair<const carve::csg::IObj, carve::mesh::Vertex<3>*> > > > > >::data_type’ has not been declared
         for (super::data_type::const_iterator j = i->second.begin(); j != i->second.end(); ++j) {
                     ^~~~~~~~~
/usr/local/include/carve/intersection.hpp:120:70: error: ‘j’ was not declared in this scope
         for (super::data_type::const_iterator j = i->second.begin(); j != i->second.end(); ++j) {
                                                                      ^
/usr/local/include/carve/intersection.hpp:120:70: note: suggested alternative: ‘jn’
         for (super::data_type::const_iterator j = i->second.begin(); j != i->second.end(); ++j) {
                                                                      ^
                                                                      jn
tools/Boolean/CMakeFiles/lib_Boolean.dir/build.make:62: recipe for target 'tools/Boolean/CMakeFiles/lib_Boolean.dir/BooleanEngine.cpp.o' failed
make[2]: *** [tools/Boolean/CMakeFiles/lib_Boolean.dir/BooleanEngine.cpp.o] Error 1
CMakeFiles/Makefile2:957: recipe for target 'tools/Boolean/CMakeFiles/lib_Boolean.dir/all' failed
make[1]: *** [tools/Boolean/CMakeFiles/lib_Boolean.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```
If anyone has experience with building this and getting through this carve error, it would be great to get some guidance. Thank you!

**Comment by bernardelli** [comment]
If anyone needs to use carve, I would recommend using the repository at b3f8ebd48a82dc536da62a24a3f20df00acc8773.

The following Dockerfile lines make PyMesh and carve work with python 3.8 under ubuntu 20.04:

```Dockerfile
RUN cd /usr/lib && git clone https://github.com/PyMesh/PyMesh.git
ENV PYMESH_PATH='/usr/lib/PyMesh'
RUN cd $PYMESH_PATH && git checkout b3f8ebd48a82dc536da62a24a3f20df00acc8773 && git submodule update --init 
RUN cd $PYMESH_PATH/third_party && mkdir build && cd build && cmake ..
RUN cd $PYMESH_PATH/third_party/build && make && make install
RUN cd $PYMESH_PATH && mkdir build && cd build && cmake .. && make
RUN cd $PYMESH_PATH && python3 setup.py install 

### fix clock func
ENV BROKEN_FILE=/usr/local/lib/python3.8/dist-packages/pymesh2-0.2.1-py3.8-linux-x86_64.egg/pymesh/timethis.py
  #This deletes first 3 line from file
RUN sed -i '1,3d' $BROKEN_FILE
  #This is a workaround
RUN printf '#!/usr/bin/env python\nfrom time import time\nclock = time\n' | cat - $BROKEN_FILE > temp && mv temp $BROKEN_FILE

```
